### ISSUE TITLE
Multiple checkboxes are showing again

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/Aghanims_Editor#103]
This is a bug, should only show once. 
![image](https://user-images.githubusercontent.com/16277198/88584445-f907da00-d094-11ea-8463-9f372ccd4075.png)

**Comment by darklordabc** [comment]
They seem to still be there but hidden, causing ability boxes to be larger than necessary.
![image](https://user-images.githubusercontent.com/16277198/88712478-261fbf80-d15d-11ea-9338-1d2e6b281693.png)

**Comment by darklordabc** [comment]
Problem number 2: The checkbox is not showing on the first ability in the extra info area (the greyed out information). For example in the below image "Ability1" should have the checkbox, because its the first ability in this hero's data, but it is not showing. 
![image](https://user-images.githubusercontent.com/16277198/88712707-7f87ee80-d15d-11ea-8f00-43360a322cd4.png)

**Comment by darklordabc** [comment]
Problem number 2 is not fixed. That checkbox will not show up if the first ability is in the default abilities field.
![image](https://user-images.githubusercontent.com/16277198/88977538-6fa90f80-d301-11ea-988d-1f062d3d420d.png)

**Comment by super5508** [comment]
It works when the override abilities have ability files.
Like Chen.
I will fix it too.

**Comment by darklordabc** [comment]
Seems to be fixed
