### ISSUE TITLE
Rename Mods to Aghanims Editor

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/Aghanims_Editor#74]
We are working on an icon now

**Comment by super5508** [comment]
@darklordabc Could you please add the screenshot here?
I changed the app title from Mod to Aghanims Editor already.

**Comment by darklordabc** [comment]
What it shows as its loading
![image](https://user-images.githubusercontent.com/16277198/87877252-940f0d00-ca20-11ea-99ff-e5fe2b922c8f.png)
What is shows after
![image](https://user-images.githubusercontent.com/16277198/87877273-b6088f80-ca20-11ea-897b-5f8370dd25dd.png)

**Comment by super5508** [comment]
@darklordabc I got it
